-- 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로 조회
-- FILE_PATH: 기본 경로 + FILE_ID + FILE_NAME + FILE_EXT
-- ORDER BY FILE_ID DESC
-- 기본 경로: /home/grep/src/

# SELECT UGB.BOARD_ID, CONCAT("/home/grep/src/", UGF.BOARD_ID, "/", UGF.FILE_ID, UGF.FILE_NAME, UGF.FILE_EXT) AS FILE_PATH

SELECT CONCAT("/home/grep/src/", RANKING.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID, RANK() OVER(ORDER BY VIEWS DESC) AS VIEW_RANK
    FROM USED_GOODS_BOARD
) AS RANKING
INNER JOIN USED_GOODS_FILE AS UGF
ON RANKING.BOARD_ID = UGF.BOARD_ID
WHERE VIEW_RANK = 1
ORDER BY FILE_ID DESC
;